# Generated by Django 3.0.4 on 2020-04-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
